name: Full Conso Download

permissions:
  contents: write

on:
  workflow_dispatch:  # DÃ©clenchement manuel

jobs:
  download-full-consumption:
    runs-on: ubuntu-latest
    env:
      ENEDIS_TOKEN: ${{ secrets.ENEDIS_TOKEN }}
      LINKY_PRM: ${{ secrets.LINKY_PRM }}
      PYTHONPATH: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv requests

      - name: Debug env   # Supprimer ce debud une fois validÃ©
        run: |
          echo "ENEDIS_TOKEN length = ${#ENEDIS_TOKEN}"
          echo "LINKY_PRM = $LINKY_PRM"

      - name: Run full consumption download script
        run: |
          python conso_api_tools/fetch_history.py

      - name: Commit consumption data to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Affichage debug
          git status
          
          # Ajouter uniquement data/
          git add data/
          
          # Commit seulement s'il y a des changements
          git diff --cached --quiet || git commit -m "ðŸ“Š Mise Ã  jour automatique des donnÃ©es de consommation"
          
          # Push vers main
          git push