name: Full Conso Download

on:
  workflow_dispatch:  # DÃ©clenchement manuel

jobs:
  download-full-consumption:
    runs-on: ubuntu-latest
    env:
      ENEDIS_TOKEN: ${{ secrets.ENEDIS_TOKEN }}
      PRM: ${{ secrets.LINKY_PRM }}
      PYTHONPATH: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv requests

      - name: Run full consumption download script
        run: |
          python conso_api_tools/fetch_history.py
