name: Full Production Download

on:
  workflow_dispatch:  # Déclenchement manuel

jobs:
  download-full-production:
    runs-on: ubuntu-latest
    env:
      HOYMILES_USER: ${{ secrets.HOYMILES_USER }}
      HOYMILES_PASSWORD: ${{ secrets.HOYMILES_PASSWORD }}
      HOYMILES_TOKEN: ${{ secrets.HOYMILES_TOKEN }}
      PYTHONPATH: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv requests

      - name: Debug env   # Supprimer ce debud une fois validé
        run: |
          echo "HOYMILES_USER = $HOYMILES_USER"
          echo "HOYMILES_PASSWORD length = ${#HOYMILES_PASSWORD}"
          echo "HOYMILES_TOKEN length = ${#HOYMILES_TOKEN}"
      - name: Run full production download script
        run: |
          python prod_api_tools/fetch_history.py
